-- MySQL Script generated by MySQL Workbench
-- Tue May 22 13:12:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Classe2B
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Classe2B
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Classe2B` DEFAULT CHARACTER SET utf8 ;
USE `Classe2B` ;

-- -----------------------------------------------------
-- Table `Classe2B`.`Tbl_Email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classe2B`.`Tbl_Email` ;

CREATE TABLE IF NOT EXISTS `Classe2B`.`Tbl_Email` (
  `Id_Email` INT NOT NULL AUTO_INCREMENT,
  `Txt_Email` VARCHAR(45) NOT NULL,
  `Is_Verified` VARCHAR(45) NOT NULL,
  `Txt_Challenge` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classe2B`.`Tbl_News`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classe2B`.`Tbl_News` ;

CREATE TABLE IF NOT EXISTS `Classe2B`.`Tbl_News` (
  `Id_News` INT NOT NULL AUTO_INCREMENT,
  `Nm_New` VARCHAR(45) NOT NULL,
  `Txt_Content_News` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_News`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classe2B`.`Tbl_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classe2B`.`Tbl_User` ;

CREATE TABLE IF NOT EXISTS `Classe2B`.`Tbl_User` (
  `Id_User` INT NOT NULL AUTO_INCREMENT,
  `Nm_First` VARCHAR(45) NOT NULL,
  `Nm_Last` VARCHAR(45) NOT NULL,
  `Txt_Username` VARCHAR(45) NOT NULL,
  `Txt_Password_Hash` VARCHAR(45) NOT NULL,
  `Txt_Password_Salt` VARCHAR(45) NOT NULL,
  `Txt_Image_Profil` VARCHAR(45) NOT NULL,
  `Txt_Description_Profil` VARCHAR(255) NOT NULL,
  `Tbl_Email_Id_Email` INT NOT NULL,
  `Tbl_News_Id_News` INT NOT NULL,
  PRIMARY KEY (`Id_User`),
  INDEX `fk_Tbl_User_Tbl_Email1_idx` (`Tbl_Email_Id_Email` ASC),
  INDEX `fk_Tbl_User_Tbl_News1_idx` (`Tbl_News_Id_News` ASC),
  CONSTRAINT `fk_Tbl_User_Tbl_Email1`
    FOREIGN KEY (`Tbl_Email_Id_Email`)
    REFERENCES `Classe2B`.`Tbl_Email` (`Id_Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_User_Tbl_News1`
    FOREIGN KEY (`Tbl_News_Id_News`)
    REFERENCES `Classe2B`.`Tbl_News` (`Id_News`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classe2B`.`Tbl_Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classe2B`.`Tbl_Project` ;

CREATE TABLE IF NOT EXISTS `Classe2B`.`Tbl_Project` (
  `Id_Project` INT NOT NULL AUTO_INCREMENT,
  `Nm_Project` VARCHAR(45) NOT NULL,
  `Txt_Image_Project` VARCHAR(45) NOT NULL,
  `Txt_Description_Project` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Project`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classe2B`.`Tbl_Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classe2B`.`Tbl_Group` ;

CREATE TABLE IF NOT EXISTS `Classe2B`.`Tbl_Group` (
  `Id_Group` INT NOT NULL AUTO_INCREMENT,
  `Nm_Group` VARCHAR(45) NOT NULL,
  `Txt_Image_Group` VARCHAR(45) NOT NULL,
  `Tbl_Project_Id_Project` INT NOT NULL,
  PRIMARY KEY (`Id_Group`),
  INDEX `fk_Tbl_Group_Tbl_Project1_idx` (`Tbl_Project_Id_Project` ASC),
  CONSTRAINT `fk_Tbl_Group_Tbl_Project1`
    FOREIGN KEY (`Tbl_Project_Id_Project`)
    REFERENCES `Classe2B`.`Tbl_Project` (`Id_Project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classe2B`.`Tbl_Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classe2B`.`Tbl_Role` ;

CREATE TABLE IF NOT EXISTS `Classe2B`.`Tbl_Role` (
  `Id_Role` INT NOT NULL AUTO_INCREMENT,
  `Nm_Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classe2B`.`Tbl_Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classe2B`.`Tbl_Comment` ;

CREATE TABLE IF NOT EXISTS `Classe2B`.`Tbl_Comment` (
  `Id_Comment` INT NOT NULL AUTO_INCREMENT,
  `Txt_Content_Comment` VARCHAR(45) NOT NULL,
  `Tbl_Project_Id_Project` INT NOT NULL,
  PRIMARY KEY (`Id_Comment`),
  INDEX `fk_Tbl_Comment_Tbl_Project1_idx` (`Tbl_Project_Id_Project` ASC),
  CONSTRAINT `fk_Tbl_Comment_Tbl_Project1`
    FOREIGN KEY (`Tbl_Project_Id_Project`)
    REFERENCES `Classe2B`.`Tbl_Project` (`Id_Project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classe2B`.`Tbl_User_Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classe2B`.`Tbl_User_Group` ;

CREATE TABLE IF NOT EXISTS `Classe2B`.`Tbl_User_Group` (
  `Tbl_User_Id_User` INT NOT NULL,
  `Tbl_Group_Id_Group` INT NOT NULL,
  INDEX `fk_Tbl_User_Group_Tbl_User_idx` (`Tbl_User_Id_User` ASC),
  INDEX `fk_Tbl_User_Group_Tbl_Group1_idx` (`Tbl_Group_Id_Group` ASC),
  CONSTRAINT `fk_Tbl_User_Group_Tbl_User`
    FOREIGN KEY (`Tbl_User_Id_User`)
    REFERENCES `Classe2B`.`Tbl_User` (`Id_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_User_Group_Tbl_Group1`
    FOREIGN KEY (`Tbl_Group_Id_Group`)
    REFERENCES `Classe2B`.`Tbl_Group` (`Id_Group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classe2B`.`Tbl_User_Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classe2B`.`Tbl_User_Role` ;

CREATE TABLE IF NOT EXISTS `Classe2B`.`Tbl_User_Role` (
  `Tbl_User_Id_User` INT NOT NULL,
  `Tbl_Role_Id_Role` INT NOT NULL,
  INDEX `fk_Tbl_User_Role_Tbl_User1_idx` (`Tbl_User_Id_User` ASC),
  INDEX `fk_Tbl_User_Role_Tbl_Role1_idx` (`Tbl_Role_Id_Role` ASC),
  CONSTRAINT `fk_Tbl_User_Role_Tbl_User1`
    FOREIGN KEY (`Tbl_User_Id_User`)
    REFERENCES `Classe2B`.`Tbl_User` (`Id_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_User_Role_Tbl_Role1`
    FOREIGN KEY (`Tbl_Role_Id_Role`)
    REFERENCES `Classe2B`.`Tbl_Role` (`Id_Role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
